Repository PlaceAndPeople/PnP, pull requests merged in 2024-12, with the labels that each got.

#4 chore : jest, rtl 설치 및 초기 설정
  jest.config.ts
  jest.setup.js
  package-lock.json
  package.json
  src/__test__/Home.test.tsx
  tsconfig.json
Labels: Chore

#5 chore: 테스트 커버리지 임계값 설정, 커버리지 제외 파일 추가
  jest.config.ts
  src/__test__/app/page.test.tsx
  src/app/page.tsx
Labels: Chore

#8 init : 디렉토리 설정
  src/apis/.gitkeep
  src/app/globals.css
  src/app/layout.tsx
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/store/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: Init

#9 chore : 코드품질관련-라이브러리-설치
  package-lock.json
  package.json
Labels: Chore

#12 init : prettier, eslint 설정
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: Init

#15 Test/#14/msw 설치 및 설정
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  cypress.config.ts
  cypress/e2e/app.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  jest.config.ts
  package-lock.json
  package.json
  src/__test__/app/page.test.tsx
  src/apis/.gitkeep
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/libs/test/jest.setup.ts
  src/mocks/handlers.ts
  src/mocks/node.ts
  src/store/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  tsconfig.json
Labels: Test

#17 bug : package.json 중복 제거
  package-lock.json
  package.json
Labels: Bug

#19 feat : 디렉토리구조 수정, 테일윈드 설정
  .prettierrc
  jest.config.ts
  src/__test__/app/page.test.tsx
  src/app/(base)/layout.tsx
  src/app/(base)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/features/.gitkeep
  src/lib/test/jest.setup.ts
  src/ui/.gitkeep
  tsconfig.json
Labels: Feat

#20 feat : 디렉토리 구조 수정
  .prettierrc
  jest.config.ts
  src/components/.gitkeep
  src/components/common/.gitkeep
  src/components/features/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: Feat

#23 feat : 공용 버튼 생성
  src/app/(base)/page.tsx
  src/components/common/Button/index.tsx
  tailwind.config.ts
Labels: Feat

#25 feat: host schema 정의
  prisma/schema.prisma
Labels: Feat

#26 init : Storybook-설치-및-설정
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  jest.config.ts
  package-lock.json
  package.json
  src/__test__/app/page.test.tsx
  src/components/.gitkeep
  src/components/common/Button/Button.stories.ts
  src/components/common/Button/Button.test.tsx
  tsconfig.json
Labels: Init

#31 [#30] feat: DB 마이그레이션 커맨드 추가
  migrations.js
  package-lock.json
  package.json
  prisma/migrations/20241208122307_init/migration.sql
  prisma/migrations/20241208140227_alter_coordinate_type/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  sql/0.truncate.sql
  sql/2.amenities.sql
  sql/3.rules.sql
  sql/6.room_rules.sql
  sql/amenities.sql
  sql/room_rules.sql
  sql/rules.sql
Labels: Feat

#39 feat : 헤더 구현
  package-lock.json
  src/app/(base)/layout.tsx
  src/app/(base)/page.tsx
  src/app/(header-footer)/layout.tsx
  src/app/(header-footer)/page.tsx
  src/components/common/Header/CompactSearchBar.tsx
  src/components/common/Header/Header.stories.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/MainLogo.stories.ts
  src/components/common/Header/MainLogo.tsx
  src/components/common/Header/UserButton.stories.ts
  src/components/common/Header/UserButton.tsx
  src/components/common/Header/UserMenu.stories.ts
  src/components/common/Header/UserMenu.tsx
  src/components/common/Header/UserMenuItem.stories.ts
  src/components/common/Header/UserMenuItem.tsx
  src/components/common/Header/UserNav.stories.ts
  src/components/common/Header/UserNav.tsx
  src/constants/menuItems.ts
  src/constants/routeURL.ts
Labels: Feat

#40 feat/#38/헤더-구현
  src/components/common/Header/Header.tsx
  src/components/common/Header/MainLogo.tsx
  src/components/common/Header/UserButton.tsx
  src/components/common/Header/UserMenu.tsx
  src/components/common/Header/UserNav.tsx
Labels: Refactor

#42 feat: node 파일 추가, prisma, prisma/client 버전 통일
  .nvmrc
  package-lock.json
  package.json
Labels: Feat, Fix

#43 feat : 카드 컴포넌트 구현
  public/images/01.avif
  public/images/02.avif
  public/images/03.avif
  public/images/04.avif
  public/images/05.avif
  public/images/06.avif
  src/app/(header-footer)/layout.tsx
  src/app/(header-footer)/page.tsx
  src/components/common/Card/Card.stories.ts
  src/components/common/Card/Card.tsx
  src/components/common/Card/CardCarousel.stories.ts
  src/components/common/Card/CardCarousel.tsx
  src/components/common/Card/CardSummary.stories.ts
  src/components/common/Card/CardSummary.tsx
  src/components/common/Header/UserNav.tsx
  src/constants/routeURL.ts
  src/utils/getActiveDotIndex.test.tsx
  src/utils/getActiveDotIndex.ts
Labels: Feat

#44 refactor : 카드 리팩토링
  package-lock.json
  src/components/common/Card/CardCarousel.tsx
  src/components/common/Card/CardSummary.tsx
  src/utils/getActiveDotIndex.test.tsx
  src/utils/getActiveDotIndex.ts
Labels: Refactor

#46 feat: 메인페이지 퍼블리싱
  jest.config.ts
  src/app/(header-footer)/components/RoomList.stories.ts
  src/app/(header-footer)/components/RoomList.tsx
  src/app/(header-footer)/layout.tsx
  src/app/(header-footer)/page.tsx
  src/components/common/Card/CardSummary.tsx
  src/components/features/.gitkeep
Labels: Feat

#48 feat : 숙소-상세페이지
  .storybook/main.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomCallendar.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenities.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomLocation.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomSpace.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewSummary.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
Labels: Feat

#50 [#29] feat: 이메일 로그인 구현, jwt 토큰 발급
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/auth/[...nextauth]/route.ts
  types/next-auth.d.ts
Labels: Feat

#51 feat : 숙소-상세페이지
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
Labels: Feat

#54 feat : 숙소-상세페이지
  package-lock.json
  package.json
  src/app/(header-footer)/components/RoomList.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingDropdown.tsx
  src/components/common/Card/RoomCard.stories.ts
  src/components/common/Card/RoomCard.tsx
  src/components/common/Card/RoomCardCarousel.stories.ts
  src/components/common/Card/RoomCardCarousel.tsx
  src/components/common/Card/RoomCardSummary.stories.ts
  src/components/common/Card/RoomCardSummary.tsx
Labels: Feat

#56 feat : 숙소-상세페이지
  components.json
  package-lock.json
  package.json
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingDropdown.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingDropdown.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomSpace.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/app/globals.css
  src/components/ui/calendar.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: Feat

#61 feat : 숙소-상세페이지
  package-lock.json
  src/app/(header-footer)/rooms/[id]/cancellation/page.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/houserules/page.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/app/(header-footer)/rooms/[id]/safety/page.tsx
  src/app/@modal/(.)rooms/[id]/cancellation/page.tsx
  src/app/@modal/(.)rooms/[id]/houserules/page.tsx
  src/app/@modal/(.)rooms/[id]/safety/page.tsx
  src/app/@modal/default.tsx
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/common/Modal/Modal.tsx
  src/constants/routeURL.ts
Labels: Feat

#60 feat: 유저 정보 조회 및 수정 API 개발
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/app/api/rooms/[roomId]/reviews/[reviewId]/route.ts
  src/app/api/rooms/[roomId]/reviews/route.ts
  src/app/api/users/[userId]/route.ts
  src/app/api/users/route.ts
  src/auth.ts
  src/errors/custom-error.ts
  src/errors/errors.ts
  src/errors/index.ts
  src/lib/server/index.ts
  src/lib/server/pagination.ts
  src/lib/server/prisma.ts
  src/lib/server/response.ts
  src/schemas/review.ts
  src/schemas/user.ts
  src/services/review.ts
  src/services/user.ts
  src/types/review.ts
  src/types/user.ts
Labels: Feat

#66 [#53] feat: 숙소 정보 조회 api
  package-lock.json
  src/app/api/rooms/[roomId]/reviews/[reviewId]/route.ts
  src/app/api/rooms/[roomId]/route.ts
  src/app/api/users/[userId]/route.ts
  src/services/room.ts
  src/types/room.ts
Labels: Feat

#64 feat/#34/fe-로그인-페이지
  package-lock.json
  package.json
  prisma/migrations/20241210081149_alter_int_to_bigint/migration.sql
  src/app/@modal/(.)login/page.tsx
  src/app/Providers.tsx
  src/app/StoreProvider.tsx
  src/app/layout.tsx
  src/app/login/EmailLoginForm.stories.tsx
  src/app/login/EmailLoginForm.tsx
  src/app/login/LoginHeader.stories.tsx
  src/app/login/LoginHeader.tsx
  src/app/login/SocialLogin.stories.tsx
  src/app/login/SocialLogin.tsx
  src/app/login/page.tsx
  src/components/common/Header/UserMenuItem.tsx
  src/components/common/Header/UserNav.tsx
  src/constants/menuItems.ts
  src/constants/routeURL.ts
  src/hooks/useEmailLogin.ts
  src/lib/store.ts
Labels: Feat

#70 feat : 숙소-상세페이지
  package-lock.json
  src/app/(header-footer)/layout.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomCallendar.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/components/common/Header/Header.tsx
Labels: Feat

#72 feat : http-client-구현
  src/apis/core/httpClient.ts
Labels: Feat

#73 [#67] feat: 숙소 스크랩 생성, 삭제, 조회 API
  package-lock.json
  prisma/schema.prisma
  src/app/api/rooms/[roomId]/scraps/route.ts
  src/lib/server/response.ts
  src/services/room.ts
Labels: Feat

#75 Feat/#68/image upload
  package-lock.json
  package.json
  src/app/api/users/image/route.ts
  src/auth.ts
  src/lib/server/index.ts
  src/lib/server/s3.ts
  src/services/user.ts
Labels: Bug, Feat, Chore, docs

#78 feat/#69/FE 서버액션 로그인 구현
  next.config.mjs
  src/app/@modal/(.)signin/page.tsx
  src/app/login/EmailLoginForm.tsx
  src/app/login/SocialLogin.stories.tsx
  src/app/login/SocialLogin.tsx
  src/app/signin/EmailLoginForm.stories.tsx
  src/app/signin/EmailLoginForm.tsx
  src/app/signin/EmailLoginFormBtn.tsx
  src/app/signin/LoginHeader.stories.tsx
  src/app/signin/LoginHeader.tsx
  src/app/signin/SocialLogin.tsx
  src/app/signin/SocialLoginFormBtn.stories.tsx
  src/app/signin/SocialLoginFormBtn.tsx
  src/app/signin/action.ts
  src/app/signin/page.tsx
  src/components/common/Header/UserButton.tsx
  src/components/common/Header/UserNav.tsx
  src/constants/routeURL.ts
  src/utils/email.ts
Labels: Feat

#84 feat : 숙소-상세페이지-api-연결
  next.config.mjs
  src/apis/.gitkeep
  src/apis/core/httpClient.ts
  src/apis/rooms/queries.test.ts
  src/apis/rooms/queries.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/error.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/lib/server/response.ts
  src/mocks/fixtures/room.json
  src/mocks/handlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/rooms/getRoom.ts
  src/mocks/handlers/rooms/index.ts
Labels: Feat

#83 Hotfix/#82/room api
  src/app/api/rooms/[roomId]/route.ts
  src/errors/errors.ts
  src/services/room.ts
  src/types/room.ts
  src/types/user.ts
  src/utils/convertor.ts
Labels: Bug, Feat, Fix, docs

#85 feat : fe-숙소-상세페이지-api-연결
  src/apis/rooms/queries.test.ts
  src/app/(header-footer)/rooms/[id]/cancellation/page.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/error.tsx
  src/app/(header-footer)/rooms/[id]/houserules/page.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/app/(header-footer)/rooms/[id]/safety/page.tsx
  src/constants/routeURL.ts
  src/mocks/handlers/rooms/getRoom.ts
Labels: Feat

#87 [#74] feat: 메인페이지 필터 모달 구현
  package-lock.json
  package.json
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/components/Filter/Accessibility.tsx
  src/app/(header-footer)/components/Filter/Amenity.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.tsx
  src/app/(header-footer)/components/Filter/CheckList.tsx
  src/app/(header-footer)/components/Filter/GuestPrefer.tsx
  src/app/(header-footer)/components/Filter/HostLanguage.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.tsx
  src/app/(header-footer)/components/Filter/PriceRange.tsx
  src/app/(header-footer)/components/Filter/ReservationOption.tsx
  src/app/(header-footer)/components/Filter/RoomAndBed.tsx
  src/app/(header-footer)/components/Filter/Tag.tsx
  src/app/(header-footer)/page.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/components/ModalSync.tsx
  src/components/common/Button/FilterButton.tsx
  src/components/common/Modal/FilterModal.tsx
  src/components/common/ModalProvider/ModalProvider.tsx
  src/hooks/useModal.ts
  src/lib/features/modal/modalSlice.ts
  src/lib/store.ts
Labels: Feat

#81 Feat/#79/service test
  .gitignore
  __tests__/mock/room.ts
  __tests__/service/unit/review.ts
  __tests__/service/unit/room.ts
  jest/backend.config.ts
  jest/backend.setup.ts
  jest/frontend.config.ts
  jest/frontend.setup.ts
  k6/run-k6.sh
  k6/scenarios/rooms/get-room.ts
  k6/utils/config.ts
  package-lock.json
  package.json
  prisma/migrations/20241215073657_init/migration.sql
  prisma/schema.prisma
  src/app/api/reservation/[orderNumber]/route.ts
  src/app/api/reservation/route.ts
  src/app/api/rooms/[roomId]/available/route.ts
  src/app/api/rooms/[roomId]/reviews/[reviewId]/route.ts
  src/app/api/rooms/[roomId]/reviews/route.ts
  src/app/api/rooms/[roomId]/scraps/route.ts
  src/app/api/users/[userId]/route.ts
  src/app/api/users/route.ts
  src/lib/server/response.ts
  src/services/room.ts
  src/types/room.ts
  src/utils/convertor.ts
  tsconfig.json
Labels: Bug, Feat, Fix, Chore, docs

#89 refactor : 숙소-상세페이지-수정
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/constants/routeURL.ts
  src/mocks/fixtures/room.json
  src/utils/formatElapsedTime.test.ts
  src/utils/formatElapsedTime.ts
  src/utils/getActiveDotIndex.test.ts
  src/utils/truncateText.test.ts
  src/utils/truncateText.ts
Labels: Refactor

#94 hotfix: 리뷰 조회 API 응답 수정 - 호스트 정보 추가
  src/services/review.ts
  src/types/review.ts
Labels: Bug, Fix

#99 feat : 리뷰-페이지-퍼블리싱
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewItem.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/app/(header-footer)/rooms/[id]/reviews/page.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/constants/routeURL.ts
  src/utils/formatElapsedTime.test.ts
  src/utils/formatElapsedTime.ts
  src/utils/formatRelativeDate.test.ts
  src/utils/formatRelativeDate.ts
Labels: Feat

#91 서비스 레이어 테스트
  __mock__/reservation.ts
  __mock__/review.ts
  __mock__/room.ts
  __mock__/user.ts
  __tests__/schema/reservation.ts
  __tests__/schema/review.ts
  __tests__/schema/user.ts
  __tests__/service/unit/reservation.ts
  __tests__/service/unit/review.ts
  __tests__/service/unit/room.ts
  __tests__/service/unit/user.ts
  jest/backend.config.ts
  src/lib/server/pagination.ts
  src/schemas/reservation.ts
  src/schemas/review.ts
  src/schemas/type.ts
  src/schemas/user.ts
  src/services/reservation.ts
  src/services/review.ts
  src/services/user.ts
  src/types/room.ts
  tsconfig.json
Labels: Bug, Feat, Fix, Chore, Test

#100 [#96] test: filtering ui 테스트 코드 추가
  src/app/(header-footer)/components/Filter/Accessibility.stories.ts
  src/app/(header-footer)/components/Filter/Accessibility.test.tsx
  src/app/(header-footer)/components/Filter/Accessibility.tsx
  src/app/(header-footer)/components/Filter/Amenity.stories.ts
  src/app/(header-footer)/components/Filter/Amenity.test.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.stories.ts
  src/app/(header-footer)/components/Filter/BuildingOption.test.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.tsx
  src/app/(header-footer)/components/Filter/CheckList.stories.ts
  src/app/(header-footer)/components/Filter/CheckList.test.tsx
  src/app/(header-footer)/components/Filter/CheckList.tsx
  src/app/(header-footer)/components/Filter/GuestPrefer.stories.ts
  src/app/(header-footer)/components/Filter/HostLanguage.stories.ts
  src/app/(header-footer)/components/Filter/HostLanguage.test.tsx
  src/app/(header-footer)/components/Filter/HostLanguage.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.stories.ts
  src/app/(header-footer)/components/Filter/KindOfRoom.test.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.tsx
  src/app/(header-footer)/components/Filter/PriceRange.stories.ts
  src/app/(header-footer)/components/Filter/ReservationOption.stories.ts
  src/app/(header-footer)/components/Filter/RoomAndBed.stories.ts
  src/app/(header-footer)/components/Filter/RoomAndBed.test.tsx
  src/app/(header-footer)/components/Filter/RoomAndBed.tsx
  src/app/(header-footer)/components/Filter/Tag.stories.ts
  src/app/(header-footer)/components/Filter/Tag.test.tsx
  src/app/(header-footer)/components/Filter/Tag.tsx
  src/components/ModalSync.tsx
  src/utils/truncateText.ts
Labels: Test

#107 feat : 리뷰-api-연결
  src/apis/reviews/queries.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewSummary.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewSummary.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  tailwind.config.ts
Labels: Feat

#110 feat : 리뷰-모달-api-연결
  src/apis/reviews/queries.test.ts
  src/apis/reviews/queries.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewItem.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewSummary.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/mocks/fixtures/reviews.json
  src/mocks/handlers/index.ts
  src/mocks/handlers/reviews/getReviews.ts
  src/mocks/handlers/reviews/index.ts
Labels: Feat

#114 feat: 숙소-상세페이지-구글맵-연동
  package-lock.json
  package.json
  public/images/locationMarker.svg
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomLocation.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomLocation.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/components/common/Map/GoogleMapView.stories.ts
  src/components/common/Map/GoogleMapView.tsx
  src/components/ui/skeleton.tsx
  src/hooks/useGoogleMap.test.ts
  src/hooks/useGoogleMap.ts
Labels: Feat

#116 feat : 숙소 상세정보 모달
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenities.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenities.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenitiesModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenitiesModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescriptionModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescriptionModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomHost.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewItem.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewSummary.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/components/common/Button/FilterButton.tsx
  src/components/common/Modal/FilterModal.tsx
  src/components/common/ModalProvider/ModalProvider.tsx
  src/constants/.gitkeep
  src/constants/modal.ts
  src/hooks/.gitkeep
  src/hooks/useModal.ts
  src/lib/features/modal/modalSlice.ts
  src/utils/.gitkeep
Labels: Feat

#121 feat : 숙소-규칙-모달
  src/app/(header-footer)/rooms/[id]/cancellation/page.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGallery.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGalleryModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomGalleryModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomCancellationModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomCancellationModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.stories.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRulesModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomRulesModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomSafetyModalButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomSafetyModalButton.tsx
  src/app/(header-footer)/rooms/[id]/houserules/page.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/app/(header-footer)/rooms/[id]/safety/page.tsx
  src/app/@modal/(.)rooms/[id]/cancellation/page.tsx
  src/app/@modal/(.)rooms/[id]/houserules/page.tsx
  src/app/@modal/(.)rooms/[id]/safety/page.tsx
  src/components/common/ModalProvider/ModalProvider.tsx
  src/constants/modal.ts
  src/hooks/useGoogleMap.ts
  src/hooks/useModal.ts
  src/utils/formatElapsedTime.ts
  src/utils/formatRelativeDate.ts
  src/utils/getActiveDotIndex.ts
  src/utils/truncateText.ts
Labels: Feat

#120 [#95] feat: filtering api, 건물 유형 제외 완료
  prisma/schema.prisma
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/components/Filter/Accessibility.stories.ts
  src/app/(header-footer)/components/Filter/Accessibility.test.tsx
  src/app/(header-footer)/components/Filter/Accessibility.tsx
  src/app/(header-footer)/components/Filter/Amenity.stories.ts
  src/app/(header-footer)/components/Filter/Amenity.test.tsx
  src/app/(header-footer)/components/Filter/Amenity.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.stories.ts
  src/app/(header-footer)/components/Filter/BuildingOption.test.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.tsx
  src/app/(header-footer)/components/Filter/CheckList.stories.ts
  src/app/(header-footer)/components/Filter/CheckList.test.tsx
  src/app/(header-footer)/components/Filter/FilterModal.tsx
  src/app/(header-footer)/components/Filter/GuestPrefer.stories.ts
  src/app/(header-footer)/components/Filter/GuestPrefer.tsx
  src/app/(header-footer)/components/Filter/HostLanguage.stories.ts
  src/app/(header-footer)/components/Filter/HostLanguage.test.tsx
  src/app/(header-footer)/components/Filter/HostLanguage.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.stories.ts
  src/app/(header-footer)/components/Filter/KindOfRoom.test.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.tsx
  src/app/(header-footer)/components/Filter/PriceRange.stories.ts
  src/app/(header-footer)/components/Filter/ReservationOption.stories.ts
  src/app/(header-footer)/components/Filter/ReservationOption.tsx
  src/app/(header-footer)/components/Filter/RoomAndBed.stories.ts
  src/app/(header-footer)/components/Filter/RoomAndBed.test.tsx
  src/app/(header-footer)/components/Filter/Tag.stories.ts
  src/app/(header-footer)/components/Filter/Tag.test.tsx
  src/app/(header-footer)/components/Filter/Tag.tsx
  src/app/api/rooms/price/route.ts
  src/app/api/rooms/route.ts
  src/services/room.ts
Labels: Feat

#126 feat/#111/FE 메세지 페이지
  src/app/(header-footer)/signin/action.test.ts
  src/app/(header-footer)/signin/action.ts
  src/app/(header-footer)/signin/components/EmailLoginForm.stories.tsx
  src/app/(header-footer)/signin/components/EmailLoginForm.tsx
  src/app/(header-footer)/signin/components/EmailLoginFormBtn.tsx
  src/app/(header-footer)/signin/components/LoginHeader.stories.tsx
  src/app/(header-footer)/signin/components/LoginHeader.tsx
  src/app/(header-footer)/signin/components/SocialLogin.tsx
  src/app/(header-footer)/signin/components/SocialLoginFormBtn.stories.tsx
  src/app/(header-footer)/signin/components/SocialLoginFormBtn.tsx
  src/app/(header-footer)/signin/page.tsx
  src/app/@modal/(.)signin/page.tsx
  src/app/messages/components/dummyMessages.ts
  src/app/messages/components/message/AllMessageFilter.stories.tsx
  src/app/messages/components/message/AllMessageFilter.tsx
  src/app/messages/components/message/AllMessageHeader.stories.tsx
  src/app/messages/components/message/AllMessageHeader.tsx
  src/app/messages/components/message/AllMessageListItem.stories.tsx
  src/app/messages/components/message/AllMessageListItem.tsx
  src/app/messages/components/message/AllMessageSearchBar.stories.tsx
  src/app/messages/components/message/AllMessageSearchBar.tsx
  src/app/messages/components/message/MessageContent.tsx
  src/app/messages/components/message/MessageHeader.stories.tsx
  src/app/messages/components/message/MessageHeader.tsx
  src/app/messages/components/message/MessageInput.stories.tsx
  src/app/messages/components/message/MessageInput.tsx
  src/app/messages/components/reservation/CustomerSupport.stories.tsx
  src/app/messages/components/reservation/CustomerSupport.tsx
  src/app/messages/components/reservation/HostInformation.stories.tsx
  src/app/messages/components/reservation/HostInformation.tsx
  src/app/messages/components/reservation/PaymentInformation.stories.tsx
  src/app/messages/components/reservation/PaymentInformation.tsx
  src/app/messages/components/reservation/ReservationContent.tsx
  src/app/messages/components/reservation/ReservationDetailInformation.stories.tsx
  src/app/messages/components/reservation/ReservationDetailInformation.tsx
  src/app/messages/components/reservation/ReservationHeader.stories.tsx
  src/app/messages/components/reservation/ReservationHeader.tsx
  src/app/messages/components/reservation/RoomInformation.stories.tsx
  src/app/messages/components/reservation/RoomInformation.tsx
  src/app/messages/components/reservation/RoomRules.stories.tsx
  src/app/messages/components/reservation/RoomRules.tsx
  src/app/messages/layout.tsx
  src/app/messages/page.tsx
  src/components/common/Header/UserHeader.tsx
  src/components/common/Header/UserMenu.tsx
  src/components/common/Header/UserMenuItem.tsx
  src/components/common/Header/UserNav.tsx
  src/constants/menuItems.ts
  src/hooks/useEmailLoginForm.test.ts
  src/hooks/useEmailLoginForm.ts
  src/types/message.ts
Labels: Feat

#125 feat : 숙소-예약-생성
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
Labels: Feat

#136 feat : 숙소-예약-API-연결
  package-lock.json
  package.json
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.ts
  src/app/(header-footer)/layout.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/types/action.ts
Labels: Feat

#138 refactor : 숙소-예약-생성-api-수정
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/constants/routeURL.ts
  src/hooks/use-toast.test.ts
  src/utils/calculatePrice.test.ts
  src/utils/calculatePrice.ts
Labels: Refactor

#140 refactor : 예약페이지-라우팅-수정
  src/apis/reservation/queries.ts
  src/app/(header-footer)/book/[orderNumber]/components/payment.tsx
  src/app/(header-footer)/book/[orderNumber]/page.tsx
Labels: Refactor

#142 feat : 숙소-예약-조회
  src/apis/reservation/actions.ts
  src/apis/reservation/queries.ts
  src/app/(header-footer)/reservation/[orderNumber]/components/payment.tsx
  src/app/(header-footer)/reservation/[orderNumber]/error.tsx
  src/app/(header-footer)/reservation/[orderNumber]/page.tsx
  src/app/(header-footer)/reservation/layout.tsx
  src/app/(header-footer)/reservation/success/page.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/constants/routeURL.ts
Labels: Feat

#144 [#129] feat: filtering api 연결
  src/apis/filters/action.ts
  src/apis/filters/queries.ts
  src/app/(header-footer)/components/Filter/Amenity.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.stories.ts
  src/app/(header-footer)/components/Filter/BuildingOption.test.tsx
  src/app/(header-footer)/components/Filter/BuildingOption.tsx
  src/app/(header-footer)/components/Filter/CheckList.tsx
  src/app/(header-footer)/components/Filter/FilterModal.tsx
  src/app/(header-footer)/components/Filter/HostLanguage.tsx
  src/app/(header-footer)/components/Filter/KindOfRoom.tsx
  src/app/(header-footer)/components/Filter/PriceRange.tsx
  src/app/(header-footer)/components/Filter/ReservationOption.tsx
  src/app/(header-footer)/components/Filter/RoomAndBed.tsx
  src/app/(header-footer)/components/Filter/Tag.tsx
  src/app/(header-footer)/components/RoomList.tsx
  src/app/(header-footer)/page.tsx
  src/app/api/rooms/count/route.ts
  src/app/api/rooms/price/route.ts
  src/components/common/Card/RoomCard.tsx
  src/components/common/Card/RoomCardCarousel.tsx
  src/components/common/Card/RoomCardSummary.tsx
  src/constants/language.ts
  src/schemas/rooms.ts
  src/services/room.ts
  src/types/room.ts
  src/utils/formatFilter.ts
Labels: Feat

#147 feat : api-에러-처리
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.ts
  src/apis/reservation/queries.ts
  src/apis/reviews/queries.ts
  src/apis/rooms/queries.ts
  src/app/(header-footer)/reservation/[orderNumber]/components/payment.tsx
  src/app/(header-footer)/reservation/[orderNumber]/error.tsx
  src/app/(header-footer)/reservation/[orderNumber]/page.tsx
  src/app/(header-footer)/rooms/[id]/error.tsx
  src/app/api/payment/route.ts
  src/app/lib/server/cookies.ts
  src/app/not-found.tsx
  src/hooks/usePayment.ts
Labels: Feat

#152 [#150] feat: filter pagination 적용
  src/apis/filters/queries.ts
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/components/filter/FilterModal.tsx
  src/app/(header-footer)/page.tsx
  src/app/api/rooms/route.ts
  src/components/common/Header/UserMenu.tsx
  src/services/room.ts
  src/types/room.ts
Labels: Feat

#153 refactor : httpClient-수정
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.test.ts
  src/apis/reservation/actions.ts
  src/apis/reservation/queries.test.ts
  src/apis/reservation/queries.ts
  src/apis/reviews/queries.test.ts
  src/apis/rooms/queries.test.ts
  src/app/lib/server/cookies.test.ts
  src/app/lib/server/cookies.ts
  src/hooks/use-toast.test.ts
  src/hooks/usePayment.ts
  src/mocks/fixtures/resetvation.json
  src/mocks/handlers/index.ts
  src/mocks/handlers/reservation/createReservation.ts
  src/mocks/handlers/reservation/getReservation.ts
  src/mocks/handlers/reservation/index.ts
  src/mocks/handlers/reviews/getReviews.ts
  src/mocks/handlers/reviews/index.ts
  src/mocks/handlers/rooms/getRoom.ts
  src/mocks/handlers/rooms/index.ts
Labels: Refactor, Test

#155 test : fe-api-테스트-코드-수정
  src/apis/reservation/queries.test.ts
  src/apis/reviews/queries.test.ts
  src/apis/rooms/queries.test.ts
Labels: Test

#156 modify/#151/FE 로그인 리다이렉트 url 변경
  src/app/(header-footer)/signin/action.ts
  src/app/(user)/messages/components/AllMessageFilter.stories.tsx
  src/app/(user)/messages/page.tsx
  src/app/(user)/wishlists/page.tsx
  src/components/common/Header/UserMenuItem.tsx
  src/types/message.ts
Labels: Modify

#160 [#145] test: useModal test 추가, fix: filter any 타입 수정
  src/app/(header-footer)/components/filter/FilterModal.tsx
  src/hooks/useModal.test.ts
Labels: Fix

#159 feat : 리뷰 생성 폼 퍼블리싱
  .storybook/preview.ts
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.test.ts
  src/apis/reservation/actions.ts
  src/apis/reviews/actions.ts
  src/apis/reviews/queries.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewForm.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewForm.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewRating.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewRating.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/components/ui/toast.tsx
  src/constants/cacheTags.ts
Labels: Feat

#170 feat : 리뷰 수정
  .storybook/decorators.tsx
  .storybook/preview.ts
  src/apis/reviews/actions.test.ts
  src/apis/reviews/actions.ts
  src/app/(header-footer)/rooms/[id]/components/information/RoomRules.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewCreateForm.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewCreateForm.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewEditButton.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewEditButton.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewEditForm.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewEditForm.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewItem.stories.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewItem.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewRating.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/constants/review.ts
  src/mocks/handlers/reviews/deleteReview.ts
  src/mocks/handlers/reviews/index.ts
  src/mocks/handlers/reviews/updateReview.ts
  src/types/review.ts
Labels: Feat

#174 [#172] hotfix: scraps -> scrap
  src/app/api/rooms/[roomId]/scrap/route.ts
Labels: Refactor

#177 feat : 숙소-스크랩-조회-퍼블리싱
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
Labels: Feat

#179 feat : 숙소-스크랩-조회-api-연결
  src/apis/rooms/queries.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.tsx
Labels: Feat
