Repository PlaceAndPeople/PnP, pull requests merged in 2025-01, with the labels that each got.

#181 feat : 숙소-스크랩-생성-api-연결
  src/apis/rooms/actions.ts
  src/apis/rooms/queries.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewEditForm.tsx
  src/constants/cacheTags.ts
  src/hooks/useRoomScrap.ts
Labels: Feat

#183 feat : 숙소 스크랩 삭제 api연결
  src/apis/rooms/actions.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.tsx
  src/hooks/useRoomScrap.ts
Labels: Feat

#186 refactor : 숙소 스크랩 mutation 관심사 분리
  src/app/(header-footer)/rooms/[id]/components/header/RoomScrapButton.tsx
  src/hooks/useRoomScrap.ts
Labels: Refactor

#189 test : 스크랩 여부 조회 테스트 코드 작성
  src/apis/rooms/queries.test.ts
  src/apis/rooms/queries.ts
  src/mocks/handlers/rooms/getRoom.ts
  src/mocks/handlers/rooms/getScrap.ts
  src/mocks/handlers/rooms/index.ts
Labels: Test

#191 test : 스크랩 추가 테스트코드 작성
  src/apis/rooms/actions.test.ts
  src/mocks/handlers/rooms/createScrap.ts
  src/mocks/handlers/rooms/index.ts
Labels: Test

#193 test : 스크랩 취소 테스트코드 작성
  src/apis/rooms/actions.test.ts
  src/apis/rooms/actions.ts
  src/mocks/handlers/rooms/deleteScrap.ts
  src/mocks/handlers/rooms/index.ts
Labels: Test

#196 refactor : 리뷰 생성 파라미터 임시수정
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewCreateForm.tsx
Labels: Refactor

#198 feat : 리뷰 권한 조회 api 연결
  src/apis/reviews/actions.test.ts
  src/apis/reviews/actions.ts
  src/apis/reviews/queries.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewCreateForm.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewCreateForm.tsx
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/constants/cacheTags.ts
Labels: Feat

#199 feat/#157/FE 여행 페이지 api 연결
  src/apis/signin/action.test.ts
  src/apis/signin/action.ts
  src/apis/trips/queries.test.ts
  src/apis/trips/queries.ts
  src/app/(header-footer)/signin/components/SocialLogin.tsx
  src/app/(user)/error.tsx
  src/app/(user)/trips/components/PreviousReservationCard.stories.tsx
  src/app/(user)/trips/components/PreviousReservationCard.tsx
  src/app/(user)/trips/components/ReservationCard.stories.tsx
  src/app/(user)/trips/components/ReservationCard.tsx
  src/app/(user)/trips/components/UpcommingReservationCard.stories.tsx
  src/app/(user)/trips/components/UpcommingReservationCard.tsx
  src/app/(user)/trips/page.tsx
  src/hooks/useEmailLoginForm.test.ts
  src/hooks/useEmailLoginForm.ts
  src/utils/categorizeReservation.test.ts
  src/utils/categorizeReservation.ts
  src/utils/email.ts
  src/utils/formatDate.test.ts
  src/utils/formatDate.ts
  src/utils/getRedirectUrl.test.ts
  src/utils/getRedirectUrl.ts
Labels: Feat

#201 test : 리뷰 작성 권한 조회 테스트코드 작성
  src/apis/reviews/queries.test.ts
  src/apis/reviews/queries.ts
  src/apis/rooms/queries.test.ts
  src/mocks/handlers/reviews/getReviewAvailable.ts
  src/mocks/handlers/reviews/index.ts
  src/mocks/handlers/rooms/getScrap.ts
Labels: Test

#203 test : 테스트코드 수정
  src/apis/rooms/queries.test.ts
  src/mocks/handlers/reservation/getReservation.ts
  src/mocks/handlers/reviews/getReviews.ts
  src/mocks/handlers/rooms/getRoom.ts
Labels: Refactor, Test

#205 feat : 숙소 예약 가능 날짜 조회 api 연결
  src/apis/rooms/queries.ts
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingButton.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingButton.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
  src/constants/cacheTags.ts
  src/hooks/useRoomBooking.ts
Labels: Feat, Refactor

#207 test : 숙소 예약 가능 날짜 조회 테스트코드 작성
  src/apis/rooms/queries.test.ts
  src/mocks/fixtures/roomAvailable.json
  src/mocks/handlers/rooms/getRoomAvailable.ts
  src/mocks/handlers/rooms/index.ts
Labels: Test

#209 feat : 숙소 예약 가능 날짜 퍼블리싱
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/hooks/useRoomAvailableDates.ts
Labels: Feat

#212 refactor : 숙소 예약 가능 날짜 리팩토링
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/hooks/useRoomAvailableDates.ts
Labels: Refactor

#214 refactor : 숙소 예약 가능 날짜 리팩토링
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingButton.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCard.tsx
  src/hooks/useRoomAvailableDates.ts
  src/hooks/useRoomBooking.ts
Labels: Refactor

#216 refactor: RoomBookingCalendar-리팩토링
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingCalendar.tsx
  src/hooks/useDateSelection.test.ts
  src/hooks/useDateSelection.ts
  src/utils/dateUtils.test.ts
  src/utils/dateUtils.ts
Labels: Refactor, Test

#218 test : 숙소예약가능날짜조회 테스트코드 작성
  src/hooks/useRoomAvailableDates.test.ts
  src/hooks/useRoomAvailableDates.ts
Labels: Test

#220 test : 숙소 스크랩 비즈니스로직 테스트코드 작성
  src/hooks/useRoomScrap.test.ts
Labels: Test

#222 test : 숙소 예약 생성 비즈니스로직 테스트코드 작성
  src/app/(header-footer)/rooms/[id]/components/booking/RoomBookingButton.tsx
  src/hooks/useRoomBooking.test.ts
  src/hooks/useRoomScrap.test.ts
Labels: Test

#224 feat : 숙소 편의시설 아이콘 적용
  src/app/(header-footer)/rooms/[id]/components/header/RoomHeader.tsx
  src/app/(header-footer)/rooms/[id]/components/header/RoomShareUrlButton.stories.ts
  src/app/(header-footer)/rooms/[id]/components/header/RoomShareUrlButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenities.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomAmenitiesModalButton.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.stories.tsx
  src/app/(header-footer)/rooms/[id]/components/information/RoomDescription.tsx
  src/app/(header-footer)/rooms/[id]/page.tsx
Labels: Feat

#226 [#172] feat: 숙소 검색
  package-lock.json
  package.json
  src/apis/filters/action.test.ts
  src/apis/filters/action.ts
  src/apis/filters/queries.test.ts
  src/apis/filters/queries.ts
  src/app/(header-footer)/components/Filter.stories.tsx
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/components/HeaderLayout.tsx
  src/app/(header-footer)/components/filter/FilterModal.tsx
  src/app/(header-footer)/components/filter/RoomAndBed.tsx
  src/app/(header-footer)/error.tsx
  src/app/(header-footer)/search/page.tsx
  src/app/StoreProvider.tsx
  src/components/common/Button/FilterButton.stories.ts
  src/components/common/Header/ExpandedSearchBar.stories.ts
  src/components/common/Header/ExpandedSearchBar.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/SearchDate.stories.tsx
  src/components/common/Header/SearchDate.tsx
  src/components/common/Header/SearchGuest.stories.tsx
  src/components/common/Header/SearchGuest.tsx
  src/components/common/Header/SearchLocation.stories.tsx
  src/components/common/Header/SearchLocation.tsx
  src/components/ui/popover.tsx
  src/mocks/fixtures/filter.json
  src/mocks/fixtures/filterRoom.json
  src/mocks/handlers/rooms/getFilterRoom.ts
  src/mocks/handlers/rooms/getFilterRoomCount.ts
  src/mocks/handlers/rooms/getFilterRoomPrice.ts
  src/mocks/handlers/rooms/index.ts
  src/schemas/rooms.ts
  src/utils/formatFilter.test.ts
  src/utils/formatFilter.ts
Labels: Feat

#228 feat : 리뷰 무한스크롤 구현
  src/apis/reviews/queries.ts
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/@modal/(.)rooms/[id]/reviews/components/RoomReviewModalContent.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
  src/hooks/useIntersectionObserver.ts
  src/hooks/useRoomReviews.ts
Labels: Feat

#232 feat : 숙소 예약 생성시 예약가능조회 캐시 무효화
  src/apis/reservation/actions.test.ts
  src/apis/reservation/actions.ts
  src/apis/reviews/queries.test.ts
  src/apis/reviews/queries.ts
Labels: Feat

#233 [#227] feat: 검색 결과 페이지 api 연결
  jest/frontend.config.ts
  jest/frontend.setup.ts
  src/apis/filters/action.test.ts
  src/apis/filters/action.ts
  src/apis/filters/queries.test.ts
  src/apis/filters/queries.ts
  src/app/(header-footer)/components/Filter.tsx
  src/app/(header-footer)/components/RoomBox.stories.ts
  src/app/(header-footer)/components/RoomBox.tsx
  src/app/(header-footer)/components/RoomList.tsx
  src/app/(header-footer)/components/filter/Filter.stories.tsx
  src/app/(header-footer)/components/filter/Filter.tsx
  src/app/(header-footer)/components/filter/FilterModal.stories.tsx
  src/app/(header-footer)/components/filter/FilterModal.tsx
  src/app/(header-footer)/components/filter/Property.stories.tsx
  src/app/(header-footer)/components/filter/Property.tsx
  src/app/(header-footer)/components/filter/ReservationOption.test.tsx
  src/app/(header-footer)/page.tsx
  src/app/(header-footer)/search/components/SearchFilter.stories.tsx
  src/app/(header-footer)/search/components/SearchFilter.tsx
  src/app/(header-footer)/search/components/SearchProperty.stories.tsx
  src/app/(header-footer)/search/components/SearchProperty.tsx
  src/app/(header-footer)/search/components/SearchResultBox.stories.ts
  src/app/(header-footer)/search/components/SearchResultBox.tsx
  src/app/(header-footer)/search/components/SearchResultLocation.stories.tsx
  src/app/(header-footer)/search/components/SearchResultLocation.tsx
  src/app/(header-footer)/search/components/SearchResultRoomList.stories.ts
  src/app/(header-footer)/search/components/SearchResultRoomList.tsx
  src/app/(header-footer)/search/page.tsx
  src/app/api/rooms/route.ts
  src/components/common/Button/FilterButton.tsx
  src/components/common/Header/ExpandedSearchBar.tsx
  src/components/common/Header/SearchDate.tsx
  src/components/common/Header/SearchGuest.tsx
  src/components/common/Header/SearchLocation.tsx
  src/hooks/useFilterRoom.test.ts
  src/hooks/useFilterRooms.ts
  src/hooks/useLocation.test.ts
  src/hooks/useLocation.ts
  src/lib/store.ts
  src/mocks/handlers/rooms/index.ts
  src/services/room.ts
  src/types/room.ts
  src/utils/formatFilter.test.ts
  src/utils/getParamFilter.test.ts
  src/utils/getParamFilter.ts
Labels: Feat

#236 refactor/#235/FE-httpclient-분리
  src/apis/core/httpClient.ts
  src/apis/reservation/actions.ts
  src/apis/reservation/queries.ts
  src/apis/reviews/actions.ts
  src/apis/reviews/queries.ts
  src/apis/rooms/actions.ts
  src/apis/rooms/queries.ts
Labels: Feat

#239 feat : 리뷰 생성/수정 시 숙소 캐시 무효화
  src/apis/reviews/actions.test.ts
  src/apis/reviews/actions.ts
  src/apis/rooms/queries.ts
  src/constants/cacheTags.ts
Labels: Feat

#241 refactor : 리뷰 생성, 삭제 시 숙소 캐시 무효화
  src/app/(header-footer)/rooms/[id]/components/review/RoomReviewList.tsx
  src/app/@modal/(.)rooms/[id]/reviews/error.tsx
  src/app/@modal/(.)rooms/[id]/reviews/page.tsx
Labels: Refactor
